### ISSUE TITLE
How do you ensure theard safe when you read Test Data from external files like excel?

### ISSUE THREAD

**Issue by araveeti1** [dilshan5/ttaf-ui-intive#2]
Hey Dilshan...,

Good work...but how do we ensure the Test Data for each scenario is threadsafe when reading the data from external files..

I dont want to use any class or static variables ..but how do you share the Data across steps once you read the Data from external files?

**Comment by araveeti1** [comment]
Full Scenario will be like:
Scenario :login to the application
Given read the Test Data for the Test case "TC" from the sheet "excel file"
When user enters login credentials
then home page should be displayed.

**Comment by dilshan5** [comment]
Hi Araveeti,
 First I would like to say that this example do not read excel data. But I would like to suggest following scenario in BDD,

  Scenario Outline: Login to the application
    Given I am on the Login Page
    When I enter User name as "<userName>"
    And I enter Paword as "<password>"
    Then I should Redirect to Home page as Sign user
    Examples:
      | userName   | password |
      | abc@qw.com | abc      |

**Comment by araveeti1** [comment]
Hi Dilshan..Thanks for the Reply...
My case is ..I dont want to pass the Parameters each step in the scenario....instead I need to read the Data from the First Step and Pass this to other steps....

Any Idea please?
